### ISSUE TITLE
"expiration" implementation issue

### ISSUE THREAD

**Issue by zerocrates** [EHRI/omeka-amazon-s3-storage-adapter#1]
There's a small but significant difference between the behavior of our old "ZendS3" adapter and this one, and it deals with the "expiration" setting.

In the Omeka core adapter, setting "expiration" means objects are stored privately and pre-signed URLs are generated to allow short-term public access to them. The implementation here of `_getAcl()` still goes along with that way of working, setting the ACL to private if some expiration was provided.

The divergence is what's actually being done with the expiration data itself. You're passing it along as "Expiration" when you put the object. I'm not sure this does anything at all (if it does do something, I don't know what). To keep in line with what the Omeka adapter does, you'd want to use `_getExpiration` in the `getUri` method.

If no expiration is set, the code you have there is fine, just returning a URL to the object. If there is a set expiration though, you want to pass the third argument to `getObjectUrl` (something like `"+{$expiration} minutes"`, for example). Passing that third argument should get it to generate a pre-signed URL for you.

**Comment by mikesname** [comment]
Thanks for clarifying that, I was a bit hazy on the use-case :wink:  

Hopefully should be fixed in #2 ...
